[[proposal]]
== _Proposal_: BIODIVERSITY DATA PUBLICATION THROUGH GBIF (GLOBAL BIODIVERSITY INFORMATION FACILITY)

=== Presentation

It is proposed in this document to involve `company` as a publisher of biodiversity data on the GBIF (Global Biodiversity Information Facility) intergovernmental platform. In the context of global biodiversity decline, species occurrence and abundance data are essential tools for planning, implementing and monitoring of conservation and sustainable use strategies. This importance is recognized on a global scale by the United Nations Sustainable Development Goals, namely SDG14 and SDG15, to which GBIF becomes instrumental for the assessment of the progress towards the goals. Likewise, Aichi Target 19 of the Convention on Biological Diversity (CBD) uses the publication of data through GBIF2 as one of the indicators to measure the Target’s compliance, by 2020. Alongside Universities, Research Institutes and Governmental Agencies, the business sector can play a key role here as it develops thousands of environmental impact assessments locally and worldwide, which annually produce millions of data. However, participation in this effort has been very low as data produced are never or very rarely made widely available. In this area, *`company`* could take a prominent position at <national / international> level, contributing with data to GBIF in an organized and systematic way. 

Therefore, notwithstanding the  necessary care with aspects of intellectual property and confidentiality, it is proposed to carry out a proof of concept to develop and evaluate a model of biodiversity data publication by <company>, which works as a case study for the company and to GBIF. This exercise would have several advantages for *`company`*, helping to consolidate its reputation at `*national* / *international*` scale as a leader in the field of sustainability and to strengthen data availability, integration and organization processes that could be used for future investments.
